### ISSUE TITLE
Rename repo to OSIPI_SDK

### ISSUE THREAD

**Issue by stadmill** [OSIPI/osipi#14]
The current name 'pypi' is confusing. Suggest renaming our repo to osipi_sdk. Need to also update webpage name and documentation to reflect the change.

**Comment by plaresmedima** [comment]
what does sdk stand for?

The name of the repo does not matter so much as long as you keep

pip install osipi

and

import osipi

On the other hand you don't want to keep changing it all the time so its
probably worth a discussion at EMB level rather than a quick change. The
naming of the repos on the OSIPI github organisation is not very consistent
- a good approach may be to always prefix it with the TF number (like some
of the others) in which case you could also do something like

TF2.3_Python_Package





Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by ltorres6** [comment]
I think just naming it "osipi" will be fine. SDK stands for software development kit, but I think that's implied. I also think that this is going to be a more general repository, not TF 2.3 specific so I'd like to avoid the TF nomenclature.

---
Luis Torres
Scientific Solutions Engineer | Flywheel
***@***.******@***.***> | Book time to meet with me<https://outlook.office.com/bookwithme/user/2de1020ae17c424082d8eb3882bbb6e4%40c88032d3-19d1-4040-b9bf-b84c29a49480/meetingtype/09705449-c7ee-4131-b1b9-3e961b18baf2?anonymous>
[Artboard 2 (8).png]<https://flywheel.io/?utm_source=signature&utm_medium=email&utm_campaign=2023emailsignature>
flywheel.io<https://flywheel.io/?utm_source=signature&utm_medium=email&utm_campaign=2021newsignature> - Sign up to receive our monthly updates<https://flywheel.io/opt-in-to-customer-communications/?utm_source=email&utm_medium=signature&utm_campaign=osmsignature>
________________________________

**Comment by stadmill** [comment]
Agree. This is just a name change of the repo, not the package. And SDK makes it clear what it is. I don't want to add TF prefixes, there are too many of these repos already.
